#!/bin/sh

try_run() {
    if [ -f "$1" ]; then
        php "$@"; exit $?
    fi
}

try_run ./Andromeda/index.php "$@"
try_run /usr/local/lib/andromeda-server/Andromeda/index.php "$@"
try_run /usr/lib/andromeda-server/Andromeda/index.php "$@"