#!/usr/bin/env bash
set -e

# supported PHP versions
VERS="70400 80000 80100"

for phpv in $VERS; do
   echo analyzing for PHP version $phpv
   conf=tools/conf/phpstan.$phpv.neon
   vendor/bin/phpstan analyse -c $conf "$@"
done
