#!/bin/bash

# supported PHP versions
VERS="70400 80000 80100"

for phpv in $VERS; do
   echo analyzing for PHP version $phpv
   conf=tools/conf/phpstan.$phpv.neon
   vendor/bin/phpstan analyse -c $conf "$@"
   ret=$?; if [ $ret != 0 ]; then exit $ret; fi
done
