#!/bin/bash

(find Andromeda -iname '*.php' | xargs cat) > combined.txt
(find Andromeda -iname '*.py' | xargs cat) >> combined.txt
(find Andromeda -iname '*.md' | xargs cat) >> combined.txt
(find wiki -iname '*.md' | xargs cat) >> combined.txt

ls -lh combined.txt
