#!/bin/bash

if [ -z "$1" ]; then echo "extension?"; exit 1; fi

rm combined.php

getfiles() {
    find $1 -name '*'$2 | grep -v "/data/\|/docs/\|/tools/\|/vendor/"
}

getfiles . $1 | grep -v combined.php | xargs cat > combined.$1

ls -lh combined.$1
