#!/bin/bash

if [ -z "$1" ]; then echo "extension?"; exit 1; fi

rm combined.php

getfiles() {
    find $1 -name '*'$2 | grep -v "/data/\|/docs/\|/tools/\|/vendor/"
}

for i in . apps/* core; do 
    echo DIR $i; echo $(getfiles $i $1 | wc -l) files
    getfiles $i $1 | xargs -d '\n' wc -l | sort -r
done
