#!/usr/bin/env bash

cd Andromeda

dostats(){
   LINES=`cat`
   echo $(echo "$LINES" | wc -l) files
   echo "$LINES" | xargs -d '\n' wc -l | sort -h
}

phpcode(){
   grep '.php\>' | grep -v _tests
}

phptests(){
   grep '.php\>' | grep _tests
}

python(){
   grep '.py\>'
}

chunk(){
   echo SCANNING $1 $2
   find $2 -type f | $1 | dostats
}

for t in phpcode phptests python; do

   if [ "$1" == "total" ]; then 
      chunk $t . | grep "SCANNING\|total\>\|files\>"
   elif [ "$1" == "totals" ]; then
      for d in . Apps/* Core; do chunk $t $d | grep "SCANNING\|total\>\|files\>"; done
   else
      for d in . Apps/* Core; do chunk $t $d; done
   fi
   echo
done
