#!/bin/bash

cd tools; if [ ! -f doctum.phar ]; then
    wget https://doctum.long-term.support/releases/latest/doctum.phar
fi; cd ..

rm -rf docs/doctum_*

php tools/doctum.phar update tools/doctum-conf.php -v

TEMPDB=$(mktemp); TEMPCONF=$(mktemp)
./andromeda-server core dbconf --driver sqlite --outfile $TEMPCONF --dbpath $TEMPDB
./andromeda-server --dbconf $TEMPCONF core install
./andromeda-server --dbconf $TEMPCONF core usage | grep "=>" |
    grep -v "\[ok\]\|\[code\]\|\[appdata\]" | sed 's/.*=> //g' | grep -v "^testutil" > docs/USAGE.txt
rm $TEMPDB $TEMPCONF
