#!/usr/bin/env bash
set -e

TAG=$1

if [ -z "$TAG" ]; then
    echo "tag required"; exit 1
fi

rm -Rf release || true
mkdir release; cd release

git clone git@github.com:irondrive/andromeda-server.git api
cd api; git checkout $TAG

rm -rf tools Andromeda/Apps/Testutil

find . -name _tests | while read -r i; do rm -rf $i; done

export XDEBUG_MODE=off
composer install --no-dev --optimize-autoloader
composer licenses --no-dev > vendor/LICENSES.txt
rm composer.json composer.lock

cd vendor/aws/aws-sdk-php

mv src src2; mkdir src; cp -av src2/*.php src/; for dir in \
    Api Arn ClientSideMonitoring Credentials data Endpoint EndpointDiscovery Exception Handler Retry S3 Signature
    do cp -av "src2/$dir" src/; done; rm -rf src2

cd src; mv data data2; mkdir data; cp -av data2/*.php data2/s3 data/; rm -rf data2

cd ../../../.. # api

cd .. # release

git clone git@github.com:irondrive/andromeda-server-docs.git docs
cd docs; git checkout $TAG; cd ..

git clone git@github.com:irondrive/andromeda-server.wiki.git docs/wiki

find . -name ".git*" | while read -r i; do rm -rf $i; done

tar -czvf andromeda-release-$TAG.tar.gz api
zip -r andromeda-release-$TAG.zip api

tar -czvf andromeda-docs-$TAG.tar.gz docs
zip -r andromeda-docs-$TAG.zip docs

ls *.tar.gz *.zip | while read -r i; do openssl sha256 $i > $i.sha256; done
