#!/bin/bash

TAG=$1

if [ -z "$TAG" ]; then
    echo "tag required"; exit 1
fi

rm -Rf release || exit 2
mkdir release; cd release

git clone git@github.com:lightray22/andromeda-server.git api

cd api; git checkout $TAG || exit 3

rm -rf tools
rm -rf apps/testApp
find . -name tests | while read -r i; do rm -rf $i; done

export XDEBUG_MODE=off
composer install --no-dev --optimize-autoloader
rm composer.json composer.lock

cd ..

git clone git@github.com:lightray22/andromeda-server-docs.git docs
git clone git@github.com:lightray22/andromeda-server.wiki.git docs/wiki

find . -name ".git*" | while read -r i; do rm -rf $i; done

tar -czvf andromeda-release-$TAG.tar.gz api
zip -r andromeda-release-$TAG.zip api

tar -czvf andromeda-docs-$TAG.tar.gz docs
zip -r andromeda-docs-$TAG.zip docs

ls *.tar.gz *.zip | while read -r i; do openssl sha256 $i > $i.sha256; done
