#!/usr/bin/env bash
set -e

cd Andromeda

if [ `which python3` ]; then
   py=`which python3`
elif [ `which python` ]; then
   py=`which python`
else
   echo "could not find python!"; exit 1
fi

$py Core/_tests/integration/main.py $@
