#!/usr/bin/env bash
set -e

cd Andromeda;

if [ "$1" == "all" ]; then
   ../vendor/bin/phpunit . -c ../tools/conf/phpunit.xml "$@"
else
   find . -iname phpunit | while read -r dir; do
      match=`echo "$dir" | grep -i "$1"`
      if [ "$1" == "" ] || [ "$match" != "" ]; then
         echo running $dir
         ../vendor/bin/phpunit $dir -c ../tools/conf/phpunit.xml "$@"; echo
      fi
   done
fi
